import { describe, it, expect, beforeAll } from "vitest";
import { promises as fs } from "fs";
import path from "path";

// The June 2026 errata for the FIRST PRINTING, guarded where it can actually be undone.
//
// The risk is not that someone retypes an error. It is that `packs/src/stonetop-lore/**`,
// `stonetop-locations/**` and `stonetop-bestiary/**` are REGENERATED by local builders
// (scripts/local/**, gitignored) whose upstream is a parsed copy of the books — and our parsed
// copy came out of first-printing PDFs. Rebuild that store without re-applying the errata and
// every correction below silently reverts on the next `build.mjs`, with a diff that looks like
// ordinary regeneration churn. Nothing else in the suite would notice.
//
// So: for each correction, the fixed wording must be PRESENT where it belongs, and the printed
// wording must be ABSENT. `absentEverywhere` is the stronger form, for strings that are simply
// wrong anywhere in the tree; the rest are pinned to their file because the superseded wording
// is legitimate elsewhere ("lacks vitals" is correct on nine other creatures, and the Thrall
// keeps their Favor).
//
// The prose record of the whole errata, including the typography-only entries that leave no
// text to check, is `free pdfs/parsed/ERRATA.md` in the pre-rename folder, which is also where
// `_tools/apply_errata.py` re-applies it to the markdown after a rebuild.

const SRC = path.resolve("packs/src");

/** Corrections pinned to the file that carries them. */
const IN_FILE = [
	// ── Book I ───────────────────────────────────────────────────────────────────────
	{ id: "b1-p106 Rites of the Land holds a Boon",
		file: "stonetop-items/playbook-moves/the-blessed/rites-of-the-land.json",
		present: ["hold 1 Boon", "hold 4 Boon instead", "Spend Boon in lieu of Stock", "\"title\": \"Boon\""],
		absent:  ["Favor"] },
	{ id: "b1-p83/540 Trade & Barter says to try again",
		file: "stonetop-items/homefront-moves/trade-and-barter.json",
		present: ["wait until next season, and then try again"],
		absent:  ["wait until next season.", "wait until next season\""] },
	{ id: "b1-p595 Denouement asks A player",
		file: "stonetop-items/special-moves/denouement.json",
		present: ["ask a player or the GM"], absent: ["ask the player or the GM"] },
	{ id: "judge-p3 Binding Arbitration",
		file: "stonetop-items/playbook-moves/the-judge/binding-arbitration.json",
		present: ["admit their wrongdoing"], absent: ["admit their wrong "] },
	{ id: "judge-p3 starting gear is scribe's tools",
		file: "stonetop-items/playbooks/the-judge.json",
		present: ["symbol of authority and scribe's tools"], absent: ["scribe's kit"] },
	{ id: "fox-p1 the Fox starts with a burglar's kit",
		file: "stonetop-items/playbooks/the-fox.json",
		present: ["either a burglar's kit or a hidden stash"], absent: ["burglar tools"] },

	// ── Book II ──────────────────────────────────────────────────────────────────────
	{ id: "b2-p79 the Specter lacks organs",
		file: "stonetop-bestiary/powers/specter.json",
		present: ["lacks organs"], absent: ["lacks vitals"] },
	{ id: "b2-p22 Aratis", file: "stonetop-lore/gods/aratis-the-lawkeeper.json",
		present: ["According to the tales:"], absent: ["According to the tales…"] },
	{ id: "b2-p64 Danu", file: "stonetop-lore/gods/danu-the-earth-mother.json",
		present: ["According to the tales:"], absent: ["According to the tales…"] },
	{ id: "b2-p224 Helior", file: "stonetop-lore/gods/helior-the-daybringer.json",
		present: ["According to the tales:"], absent: ["According to the tales…"] },
	{ id: "b2-p176 the Frozen Wastes sets its tier bold",
		file: "stonetop-locations/regions/the-frozen-wastes.json",
		present: ["<strong>On a 6-</strong>, they don’t mark XP—this band"], absent: [] },
	{ id: "setting-overview p.3 tradesfolk include a potter, not a cobbler",
		file: "stonetop-locations/settlements/the-village-of-stonetop.json",
		present: ["tradesfolk (potter, midwife, publican, smith, tanner)"], absent: ["cobbler"] },
	{ id: "setting-overview p.3 crackpot scholar",
		file: "stonetop-journals/setting-overview.json",
		present: ["some crackpot scholar from the south"], absent: ["crack-job"] },

	// ── The two reference journals, generated from the item sources above ─────────────
	{ id: "reference journal: moves", file: "stonetop-journals/reference-journals/moves.json",
		present: ["wait until next season, and then try again", "ask a player or the GM"],
		absent:  ["ask the player or the GM"] },
	{ id: "reference journal: playbook moves", file: "stonetop-journals/reference-journals/playbook-moves.json",
		present: ["hold 1 Boon", "admit their wrongdoing"],
		absent:  ["hold 1 Favor", "admit their wrong "] },
];

/** Wording that is simply wrong now, wherever it turns up. */
const ABSENT_EVERYWHERE = [
	["b2-p69", "Lady of the Crows"],          // she is the Lady of Crows
	["b2-p154", "compan-ions"],               // a PDF line-break hyphen
	["b2-p156", "And soon, soon,"],
	["b2-p157", "Portugese"],
	["b2-p275", "a a muddy slum"],
	["b2-p408", "Vitrification can be reserved"],
	["b2-p532", "depelete"],
	["b2-p536", "cyrstals"],
	["b1-p99", "population boon"],
	["b1-p255", "spring burts forth"],
	["b1-p81/528", "an insert class that"],
	["b1-p116", "service though dreams"],
	["b1-p121", "wordly life"],
	["b1-p132", "out if its misery"],
	["b1-p159", "well-equiped"],
	["b1-p584", "stop becoming a PC"],
	["gm-p2", "unlcear"],
];

async function findJsonFiles(dir) {
	const entries = await fs.readdir(dir, { withFileTypes: true });
	const nested = await Promise.all(entries.map(async entry => {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) return findJsonFiles(full);
		return entry.name.endsWith(".json") ? [full] : [];
	}));
	return nested.flat();
}

describe("first-printing errata stays applied to shipped content", () => {
	/** @type {Map<string, string>} repo-relative path → raw text */
	const files = new Map();

	beforeAll(async () => {
		for (const full of await findJsonFiles(SRC)) {
			files.set(path.relative(SRC, full).split(path.sep).join("/"), await fs.readFile(full, "utf8"));
		}
	});

	// Both spellings of the apostrophe: pack prose is a mix of straight and typographic, and a
	// guard that only knew one of them would pass on a revert that used the other.
	const variants = s => (s.includes("'") ? [s, s.replaceAll("'", "’")] : [s]);
	const has = (text, needle) => variants(needle).some(v => text.includes(v));

	it.each(IN_FILE)("$id", ({ file, present, absent }) => {
		const text = files.get(file);
		expect(text, `${file} is missing — has the pack source been renamed or regenerated away?`).toBeTypeOf("string");
		for (const needle of present) expect(has(text, needle), `${file} should contain ${JSON.stringify(needle)}`).toBe(true);
		for (const needle of absent) expect(has(text, needle), `${file} still carries the superseded ${JSON.stringify(needle)}`).toBe(false);
	});

	it.each(ABSENT_EVERYWHERE)("[%s] %s appears nowhere in packs/src", (_id, needle) => {
		const guilty = [...files].filter(([, text]) => has(text, needle)).map(([rel]) => rel);
		expect(guilty, `superseded wording reintroduced — re-run free pdfs/parsed/_tools/apply_errata.py, then the content generator`).toEqual([]);
	});

	// The Thrall's Favor is a DIFFERENT pool from the Blessed's, and the errata does not touch
	// it. Pinned so a future "rename Favor to Boon" sweep cannot quietly take it too.
	it("leaves the Thrall's Favor alone", () => {
		const thrall = files.get("stonetop-items/post-death-inserts/thrall.json");
		expect(thrall).toContain("Favor");
		expect(files.get("stonetop-items/post-death-moves/thrall/favor.json")).toContain("Favor");
	});

	// Likewise the nine creatures whose armor genuinely lacks vitals; only the Specter moved.
	it("leaves every other creature's 'lacks vitals' alone", () => {
		const still = [...files].filter(([rel, text]) => rel.startsWith("stonetop-bestiary/") && text.includes("lacks vitals"));
		expect(still.length).toBeGreaterThan(0);
		expect(still.map(([rel]) => rel)).not.toContain("stonetop-bestiary/powers/specter.json");
	});
});
