import { describe, it, expect } from "vitest";
import { readRepo } from "../fakes/css.js";
import {
	legacyYearName, generatedYearNames, planYearPageRenames, renameSeasonYearPages,
} from "../../module/migration/season-year-page-names.js";
import { yearLabel } from "../../module/seasons/seasons-chronicle.js";
import { SYSTEM_ID } from "../../module/system-id.js";

// A campaign year used to be called "First Year" and is now "Year One". The header's clock and
// the picker's chip build that string fresh every render, so they changed with the function —
// but a Chronicle page carries its name in the world's data, written once when the year was
// first recorded, and a closed-out year is never re-recorded. Hence a sweep.

const page = (id, name, year) => ({
	_id: id,
	name,
	flags: year == null ? {} : { [SYSTEM_ID]: { chronicleYear: year } },
});

describe("legacyYearName", () => {
	it("reproduces the scheme the old pages were named under", () => {
		expect(legacyYearName(1)).toBe("First Year");
		expect(legacyYearName(2)).toBe("Second Year");
		expect(legacyYearName(20)).toBe("Twentieth Year");
	});

	// The old scheme spelled 1–20 out and only then fell back to a numeric ordinal, so eleven
	// is "Eleventh Year" and not "11th Year" — get the boundary wrong and a whole band of
	// pages goes unrecognised and keeps its old name forever.
	it("carries the numeric ordinal past twenty, exception and all", () => {
		expect(legacyYearName(11)).toBe("Eleventh Year");
		expect(legacyYearName(21)).toBe("21st Year");
		expect(legacyYearName(22)).toBe("22nd Year");
		expect(legacyYearName(23)).toBe("23rd Year");
		expect(legacyYearName(111)).toBe("111th Year");
		expect(legacyYearName(101)).toBe("101st Year");
	});
});

describe("planYearPageRenames", () => {
	it("renames a page still wearing the old ordinal name", () => {
		expect(planYearPageRenames([page("a", "First Year", 1), page("b", "Third Year", 3)]))
			.toEqual([{ _id: "a", name: "Year One" }, { _id: "b", name: "Year Three" }]);
	});

	// The whole safety argument: it recognises a GENERATED name and writes one, so the second
	// pass has nothing left to match and no gate is needed to stop it.
	it("is a no-op once it has run", () => {
		const pages = [page("a", "First Year", 1), page("b", "21st Year", 21)];
		const first = planYearPageRenames(pages);
		expect(first).toHaveLength(2);
		for (const row of first) pages.find(p => p._id === row._id).name = row.name;
		expect(planYearPageRenames(pages)).toEqual([]);
	});

	// A GM who has titled a page has said something this cannot improve on.
	it("never touches a name a human chose", () => {
		expect(planYearPageRenames([
			page("a", "Year One — the Hillfolk winter", 1),
			page("b", "The Long Dark", 2),
			page("c", "", 3),
		])).toEqual([]);
	});

	// The flag is what makes a page one of these, not the journal it sits in or its name.
	it("ignores pages that are not year pages at all", () => {
		expect(planYearPageRenames([
			page("a", "First Year", null),
			page("b", "First Year", 0),
			page("c", "First Year", "spring"),
			{ _id: "d", name: "First Year" },
		])).toEqual([]);
	});

	// A page whose year lives under somebody else's flag scope is somebody else's page — the name
	// matching is not enough on its own, or the sweep would rename anything called "First Year".
	it("reads the flag out of the system's own scope and no other", () => {
		expect(planYearPageRenames([
			{ _id: "a", name: "First Year", flags: { other: { chronicleYear: 1 } } },
		])).toEqual([]);
	});

	// The set it recognises is generated by the very function the sheet renders, so the two
	// cannot drift: change `yearLabel` again and the sweep follows it without an edit here.
	it("recognises whatever the live label function currently produces", () => {
		expect(generatedYearNames(4)).toContain(yearLabel(4));
		expect(generatedYearNames(4)).toContain(legacyYearName(4));
	});
});

describe("renameSeasonYearPages", () => {
	/** A stand-in journal: live pages in, one recorded update call out. */
	function journal(pages) {
		const calls = [];
		return {
			pages,
			calls,
			async updateEmbeddedDocuments(type, updates) { calls.push({ type, updates }); },
		};
	}

	it("issues one update for the pages that moved", async () => {
		const entry = journal([
			{ id: "a", name: "First Year", flags: { [SYSTEM_ID]: { chronicleYear: 1 } } },
			{ id: "b", name: "Year Two",   flags: { [SYSTEM_ID]: { chronicleYear: 2 } } },
		]);
		expect(await renameSeasonYearPages(entry)).toBe(1);
		expect(entry.calls).toEqual([{
			type: "JournalEntryPage",
			updates: [{ _id: "a", name: "Year One" }],
		}]);
	});

	// Every world that has already been swept, and every world that never had a page, pays
	// this cost on every load forever — so it must not write, and must not clone the journal.
	it("writes nothing when there is nothing to do", async () => {
		const clean = journal([{ id: "a", name: "Year One", flags: { [SYSTEM_ID]: { chronicleYear: 1 } } }]);
		expect(await renameSeasonYearPages(clean)).toBe(0);
		expect(clean.calls).toEqual([]);
		expect(await renameSeasonYearPages(journal([]))).toBe(0);
		expect(await renameSeasonYearPages(undefined)).toBe(0);
		// ...and it decides that off the LIVE pages: `toObject()` is a recursive clone of a
		// page's whole source data, so cloning a journal to discover there is nothing to do
		// would cost more than the rename ever does. The stand-in pages above have no such
		// method, so a call would throw rather than pass quietly.
		expect(readRepo("module/migration/season-year-page-names.js")).not.toMatch(/\.toObject\(/);
	});
});

describe("the sweep's place in the load", () => {
	const READY = readRepo("module/hooks/Ready.js");

	// Primary GM only — it writes, and two connected GMs would both issue the same update.
	it("runs on every load, gated to the primary GM, and cannot take the load down with it", () => {
		expect(READY).toContain("renameAllSeasonYearPages");
		const gated = READY.slice(READY.indexOf("if (isPrimaryGM()) {"));
		expect(gated).toContain("await renameAllSeasonYearPages();");
		expect(gated).toMatch(/try \{ await renameAllSeasonYearPages\(\); \}\s*\n\s*catch/);
	});
});
